

- name: MySQL | install mysql packages
  apt: pkg={{ item }} state=installed
  become: true
  with_items:
   - mysql-server

- name: config
  shell: >
    bash /docker/provisioning/roles/mysql/templates/config.sh