

- name: add yarn (key)
  apt_key:
      url: https://dl.yarnpkg.com/debian/pubkey.gpg
      state: present

- name: add yarn deb
  apt_repository:
      repo: deb https://dl.yarnpkg.com/debian/ stable main
      state: present
      filename: 'yarn'

- name: install yarn
  apt: name=yarn state=present