- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: update apt cache
      apt: update_cache=yes
  vars:
    lsb_release: stretch
  roles:
    - curl
    - apt-transport-https
    - lsb-release
    - ca-certificates
    - ufw
    - sudo
    - git
    - mysql
    - make
    - php
    - nginx
    - phpunit
    - composer
    - node
    - yarn
    - service
